// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo04BMni2LBjbxK6pH17z41Bd6WF_v7fo',
    appId: '1:57644205423:web:5a92c12378969a141b949a',
    messagingSenderId: '57644205423',
    projectId: 'ecommerce-app-fd252',
    authDomain: 'ecommerce-app-fd252.firebaseapp.com',
    storageBucket: 'ecommerce-app-fd252.appspot.com',
    measurementId: 'G-3YYKPVZFHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBDuInH8u0w4oBrIFwXlb_TrCiXwDCYg',
    appId: '1:57644205423:android:38d8e4da582a8da21b949a',
    messagingSenderId: '57644205423',
    projectId: 'ecommerce-app-fd252',
    storageBucket: 'ecommerce-app-fd252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXuIV4ge2PsMIXu8L2BkDmUbSbgV3xjwo',
    appId: '1:57644205423:ios:a30ed295c1be12591b949a',
    messagingSenderId: '57644205423',
    projectId: 'ecommerce-app-fd252',
    storageBucket: 'ecommerce-app-fd252.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXuIV4ge2PsMIXu8L2BkDmUbSbgV3xjwo',
    appId: '1:57644205423:ios:62b0dfaded32b6991b949a',
    messagingSenderId: '57644205423',
    projectId: 'ecommerce-app-fd252',
    storageBucket: 'ecommerce-app-fd252.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
